FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy producer script
COPY coinbase_producer.py .

# Run producer
CMD ["python", "coinbase_producer.py"]
